### PR TITLE
Start button improvements

### PR DESCRIPTION
**Pull request by archeYR**
SunXP now uses a Start logo bitmap from Explorer resources (just like in the Luna theme) rather than have it fused in one bitmap. Also changed the vaules in .ini files to display a Start button bitmap correctly.
przechwytywanie

### CODE REVIEW

**Comment by sagudev** [comment]
@katahiromz can you make changes to svg and png too.

**Comment by cernodile** [comment]
Looks good to me.

**Comment by cernodile** [comment]
@sagudev I imagine it's not that hard to remove the logo. I could attempt to do it myself.

**Comment by cernodile** [comment]
Looks good for merge @sagudev

**Review by cernodile — APPROVED** [review]

**Pull request merged**
