### PR TITLE
resize buttons and update start.svg

### PR DESCRIPTION
**Pull request by katahiromz**
Resized some images and improved start button.

### CODE REVIEW

**Comment by sagudev** [comment]
butons does not have x in it but r or 0

**Comment by sagudev** [comment]
All curent work is for #2

**Review by cernodile — COMMENTED** [review]
Not really a fan of this "r" thing on exit, neither numbers on buttons. I think general public is more used to the minus, rectangle and cross buttons. Also not sure how .svg can help as we need all assets in theme as bitmaps.

**Comment by sagudev** [comment]
As I allready said vector images are great as you can get any resolution, we just need to find way to convert them to bmp while compiling

**Comment by sagudev** [comment]
> Not really a fan of this "r" thing on exit, neither numbers on buttons. I think general public is more used to the minus, rectangle and cross buttons.

Can't agree more. @katahiromz can you fix this.

**Comment by katahiromz** [comment]
These images are using Marlett font. It requires Windows to display the images correctly.

**Comment by sagudev** [comment]
@katahiromz Images that you create?

**Comment by katahiromz** [comment]
Yes.

**Comment by sagudev** [comment]
Maybe @cernodile was right. It would be much easier to directly make BMP files, except if you find any options to convert svg to bmp that imageCount will work.

**Comment by katahiromz** [comment]
I can convert svg to bmp by exporting.

**Comment by sagudev** [comment]
But what about icons sections (look at #2)

**Comment by katahiromz** [comment]
But they are balloon's close buttons.

**Comment by sagudev** [comment]
Please, do same thing for startbutton which had 3. icons too.
https://github.com/sagudev/SunXP/blob/master/bitmaps/NORMAL_STARTBUTTON.bmp

**Review by cernodile — CHANGES_REQUESTED** [review]
Please rename all baloon files with balloon.

**Comment by cernodile** [comment]
Please edit the .rc file to redirect to your output bmp files.

**Comment by sagudev** [comment]
@katahiromz It's working. Can you please document how you make from svg to bmp. And then other people can halp you making all other icons. I will close this PR when all icons will be ready

**Comment by sagudev** [comment]
Ok. Now HOWTO is ready so everybody can help with icons. Do not forget to reference HOWTO in designconcept.md

**Comment by sagudev** [comment]
It would be nice and clener to automate svg to bmp process with cmake in compiling. And as there are currently 2 steps for conversion (svg -> png -> bmp) it would be nice to remove png step (svg -> bmp). @katahiromz Can you please do not put bmp to output folder but to bitmaps folder. And thanks for your work

**Comment by sagudev** [comment]
Ok thanks, now we just need to create all other icons. Happy drawing.

**Comment by sagudev** [comment]
Reopen PR to https://github.com/sagudev/SunXP/tree/icons_test

**Pull request closed without merging**
