### PR TITLE
Update CMakeLists to work with ROS

### PR DESCRIPTION
**Pull request by cernodile**
Allows you to `ninja sunxp.msstyles` when building ROS.

### CODE REVIEW

**Comment by sagudev** [comment]
https://www.reactos.org/forum/viewtopic.php?f=4&t=16999&sid=f91aa6dcaad9d7e9de00bd21f1164a27

**Comment by cernodile** [comment]
@sagudev better?

**Comment by sagudev** [comment]
´You can build this by creating a new directory in your [ReactOS](https://github.com/reactos/reactos) source. Navigate to reactos/Resources/Themes and create a new directory called "SunXP" (caps matter). Copy the contents of this repository there, reconfigure your ROSBE (flush all CMake cache) and build it using `ninja sunxp.msstyles`. And do not forget to add that path to `boot/bootdata/packages/reactos.dff.in`. Then also add it to the `dir_to_num macro` in `sdk/cmake/CMakeMacros.cmake` (using the number you assigned).´ sounds much better

**Comment by sagudev** [comment]
Tnx for your work @cernodile !!!

**Pull request merged**
